version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "phpcompatibility/php-compatibility"
        versions: "dev-develop"
    versioning-strategy: increase-if-necessary
