name: Code Quality

on: push

jobs:
  phpcs:
    name: PHP Coding Standards
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Configure Composer cache
        uses: actions/cache@v3.2.5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-ansi --no-progress

      - name: Run Coding Standards Tests
        run: composer phpcs

  phpstan:
    name: PHP Code Analysis
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0']
        dependency-versions: ['locked']
        include:
          - php-versions: 7.4
            dependency-versions: lowest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Configure Composer cache
        uses: actions/cache@v3.2.5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-versions }}-${{ matrix.dependency-versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-versions }}-${{ matrix.dependency-versions }}-composer-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-${{ matrix.php-versions }}-${{ matrix.dependency-versions }}-composer-

      - name: Install dependencies
        run: |
          if [ ${{ matrix.dependency-versions }} == 'lowest' ]; then
            composer update --prefer-lowest --no-interaction --no-ansi --no-progress
            composer update phpstan/phpstan
          else
            composer install --no-interaction --no-ansi --no-progress
          fi

      - name: Run Static Code Analysis
        run: composer analyse
